import pytest
import sqlalchemy as sa
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

import app.models  # noqa: F401 — registers all models on Base.metadata
from app.db.base import Base
from app.db.session import get_db
from app.main import app

# Supabase's auth.users table lives outside our app's metadata (Supabase manages it — it
# already exists in the real Postgres database migrations run against). Profile.id has a
# foreign key to it, so this stand-in lets SQLite test schema creation resolve that FK; it
# has no effect on real Alembic migrations, which are hand-written, not autogenerated.
if "auth.users" not in Base.metadata.tables:
    sa.Table(
        "users",
        Base.metadata,
        sa.Column("id", sa.Uuid(as_uuid=True), primary_key=True),
        schema="auth",
    )


@pytest.fixture()
def db_session():
    engine = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    # SQLite has no notion of Postgres schemas ("public", "auth") — treat them as unscoped
    # for this test engine only. Real Postgres migrations are unaffected.
    engine = engine.execution_options(schema_translate_map={"public": None, "auth": None})
    Base.metadata.create_all(engine)
    testing_session_local = sessionmaker(bind=engine, autoflush=False, autocommit=False)

    session = testing_session_local()
    try:
        yield session
    finally:
        session.close()
        Base.metadata.drop_all(engine)
        engine.dispose()


@pytest.fixture(autouse=True)
def _reset_rate_limiter():
    # The AI rate limiter is a shared module-level instance; reset it before each test so counts
    # don't accumulate across the suite and cause spurious 429s.
    from app.api.deps import ai_rate_limiter

    ai_rate_limiter.reset()
    yield


@pytest.fixture()
def client(db_session):
    def override_get_db():
        yield db_session

    app.dependency_overrides[get_db] = override_get_db
    try:
        with TestClient(app) as test_client:
            yield test_client
    finally:
        app.dependency_overrides.pop(get_db, None)
